source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'rails-api'
gem 'puma'
gem 'tzinfo-data'

gem 'sidekiq'
gem 'sidekiq-scheduler', '~> 2.0'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'mongoid', '~> 5'

gem 'spring', :group => :development


